theme = "hello-friend-ng"
relativeURLs = true
baseURL = "/"
title = "denis.codes"
author = "Denis Maximov"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 10
languageCode = "en-us"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "software engineer / consultant"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[[params.logo]]
logoCursorColor = "#fff"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

    # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:nobody@example.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/denismaxim0v"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/denis-maximov-a5b79a140/"

[languages]
  [languages.en]
    title = "Denis Maximov"
    subtitle = "software engineer/consultant"
    keywords = ""
    copyright = '<a href="https://github.com/denismaxim0v" target="_blank" rel="noopener">github</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "denis.codes"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
